spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/Library
        username: postgres
        password: felipevictor5120_
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true